### ISSUE TITLE
How to build Tensorflow lite into shared library

### ISSUE THREAD

**Issue by mexeniz** [take-iwiw/CNN_NumberDetector#1]
Hello! I am trying to build Tensorflow Lite into shared library on CentOS 7.
To build a static library, I followed these steps.
```
cd tensorflow
make -f tensorflow/lite/tools/make/Makefile TARGET=linux TARGET_ARCH=x86_64 -j 8
# Output: tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a
```
I found that your repository contains this shared library https://github.com/iwatake2222/CNN_NumberDetector/blob/master/05_TensorflowLite_CPP/external_libs/tensorflow_prebuilt/linux-cpu-x86_64/libtensorflowlite.so.
How did you compile that file?

**Comment by iwatake2222** [comment]
Hi.
The following is the commands I used to make libtensorflowlite.so on Ubuntu 16.04 

```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout 5d43d943153836f6c3bafd97d6bedbc124b99e37
bazel build '//tensorflow/lite:libtensorflowlite.so'
```

5d43d943153836f6c3bafd97d6bedbc124b99e37 is just the version I used. I remember the build failed when I used another version, but you can try with the latest version of master branch. It might be okay now.


FYI:
Although it's written in Japanese, this my article might help you. (with google translation)
https://qiita.com/iwatake2222/items/d998df1981d46285df62

**Comment by mexeniz** [comment]
@iwatake2222 Thank you very much!
Your instruction works fine with that commit. However, I am using TF v1.13.1 which is 2-week older than that commit.
It fails, because `//tensorflow/lite:libtensorflowlite.so` package is not available in v.1.13.1 .
I came up with building by Makefile instead as the followings:
```
git clone -b v1.13.1 https://github.com/tensorflow/tensorflow.git
cd tensorflow
./tensorflow/lite/tools/make/download_dependencies.sh
sed "s/^CXXFLAGS := .*/CXXFLAGS := -O3 -DNDEBUG -fPIC/" -i tensorflow/lite/tools/make/Makefile
sed "s/^CFLAGS := .*/CFLAGS := -fPIC/" -i tensorflow/lite/tools/make/Makefile
make -f tensorflow/lite/tools/make/Makefile TARGET=linux TARGET_ARCH=x86_64 -j6
rm -rf tensorflow/lite/tools/make/gen/linux_x86_64/obj/tensorflow/lite/examples \
        tensorflow/lite/tools/make/gen/linux_x86_64/obj/tensorflow/lite/tools/benchmark
mkdir -p /tmp/lib/tensorflow_lite && \
        gcc -shared -o /tmp/lib/tensorflow_lite/libtensorflowlite.so \
        `find tensorflow/lite/tools/make/gen/linux_x86_64/obj -type f`
```

PS. I will use your steps when I upgrade TF to newer version.
